### ISSUE TITLE
about running in the web browser

### ISSUE THREAD

**Issue by Puni89** [aki77/atom-open-html-in-browser#5]
after instaling the package i cant run the project in browser 
it showing error like
Error: spawn cmd ENOENT
Error: spawn cmd ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by dhruvbpatel** [comment]
> 
> 
> after instaling the package i cant run the project in browser
> it showing error like
> Error: spawn cmd ENOENT
> Error: spawn cmd ENOENT
> at exports._errnoException (util.js:1022:11)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
> at onErrorNT (internal/child_process.js:359:16)
> at _combinedTickCallback (internal/process/next_tick.js:74:11)
> at process._tickCallback (internal/process/next_tick.js:98:9)

I am facing same error , can anybody help me with that  ?
